### PR TITLE
Misc frontend backend linking

### PR DESCRIPTION
**Pull request by s-naik**
renamed modules to 'celesta'
updated backend structure
preliminary HTTP requests made

### CODE REVIEW

**Comment by hydrofluorich** [comment]
~~Should be good to go once CL-21 is merged.~~
Ignore this, per https://github.com/uwcbc/celesta/pull/6

**Comment by roselynh100** [comment]
with the introduction of your backend changes, can the `celesta` folder be deleted? or does it still serve a purpose

**Review by hydrofluorich — APPROVED** [review]
Approved provided that [Roselyn's question](https://github.com/uwcbc/celesta/pull/5#issuecomment-1696561915) is addressed.

**Comment by s-naik** [comment]
> with the introduction of your backend changes, can the `celesta` folder be deleted? or does it still serve a purpose

Yes it still serves a purpose. it works in tandem with the backend folder to set up the database/urls

**Review by roselynh100 — APPROVED** [review]

**Pull request merged**
